Update PIP_VERSION to latest released pip
Without this change, building ironic-image with master ironic fails with
this error:

ERROR: Cannot install oslo-concurrency 7.2.0 (from
/tmp/all-wheels/oslo_concurrency-7.2.0-py3-none-any.whl) and
oslo-concurrency 7.3.0 (from
/tmp/all-wheels/oslo_concurrency-7.3.0-py3-none-any.whl) because these
package versions have conflicting dependencies.

The conflict is caused by:
    The user requested oslo-concurrency 7.2.0 (from /tmp/all-wheels/oslo_concurrency-7.2.0-py3-none-any.whl)
    The user requested oslo-concurrency 7.3.0 (from /tmp/all-wheels/oslo_concurrency-7.3.0-py3-none-any.whl)

pip-24.1 is from June 2024, so an update is also overdue for the "update
these regularly" comment to be accurate.